### ISSUE TITLE
Error "Failed to Create Security Group" occurs when providing long description during group creation.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/users#114]
## Expected behavior
Users should be able to create security groups with detailed descriptions without encountering errors. The system should allow the creation of security groups regardless of the length of the description provided.

## Steps to reproduce the issue
Log in to the App with valid credentials.
Navigate to Permissions tab.
Click on 'CREATE SECURITY GROUP' option.
Fill in the required fields for the security group, including a detailed description exceeding a certain character limit.
Attempt to create the security group.
Observe the error message "Failed to create security group" displayed on the screen.

## Environment details
App version: MAIN-92E369A
App Environment: DEV

## Additional information
https://jam.dev/c/d0ed3ed9-938a-47f6-b157-1d844512e2b0

**Comment by dt2patel** [comment]
Show character count progress against limit. I assume Ionic has a default attribute for this that can be added to input fields.

https://ionicframework.com/docs/api/input#input-counter

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.11.0. Hence, closing this .
