### ISSUE TITLE
Toast message displayed while selecting permissions for a security group.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/users#126]
## Description:
Currently, when selecting permissions for a security group, a toast message is displayed for each individual permission selected. While this provides immediate feedback to the user, it can become repetitive and intrusive, especially when multiple permissions are selected in quick succession.

To enhance user experience and reduce notification overload, I propose the following improvements to the toast message behavior:

**Confirmation Dialog**: Instead of immediate feedback with toast messages, we can introduce a confirmation dialog that appears after the user has finished selecting permissions. This dialog can summarize all the selected permissions and allow the user to confirm their selections before proceeding.

**Settings Option**: Provide users with the option to customize notification preferences in their settings. This could include the ability to toggle on/off toast messages for permission selections or specify the frequency of notifications.

These enhancements will not only improve the user experience but also contribute to a more efficient and user-friendly interface for managing security permissions within the application.

## Additional information
https://jam.dev/c/00092800-66ec-49f9-8c47-2dc7dd5f8faa

**Comment by Adameddy26** [comment]
@dt2patel : Should I reopen this issue? Please confirm.

## These two approaches can be used to handle this issue.
Confirmation Dialog: Instead of immediate feedback with toast messages, we can introduce a confirmation dialog that appears after the user has finished selecting permissions. This dialog can summarize all the selected permissions and allow the user to confirm their selections before proceeding.

Settings Option: Provide users with the option to customize notification preferences in their settings. This could include the ability to toggle on/off toast messages for permission selections or specify the frequency of notifications.

**Comment by dt2patel** [comment]
Sure go ahead. Turn it into a feature request

**Comment by dt2patel** [comment]
Closing this issue since if we summarize permission changes into a single toast then the character length would exceed good UX.

Option to save permission notifications would require saving in backend and then we'd have to scope the impact of this feature in all apps. For the improvement we're looking for it would be too much effort.
