### ISSUE TITLE
Scrollbar position not resetting when switching security groups

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/users#130]
## Expected behavior
Upon switching to a different security group, the scrollbar position should automatically reset to the top of the page, ensuring users have access to the beginning of the content without needing to manually scroll.

## Steps to reproduce the issue
Open the application and navigate to the security groups section.
Scroll down within a security group to view content beyond the initial viewport.
Switch to another security group.
Observe that the scrollbar position remains at its scrolled-down position instead of resetting to the top.

## Environment details
App version: MAIN-92E369A
App environment: DEV

## Additional information
https://jam.dev/c/8ff3ba83-a6c9-4980-a0c7-ab85a4332621

**Comment by dt2patel** [comment]
As of now this is expected behavior or else the user would lose sight of the security group that they have selected and therefor disorienting the user.
