### ISSUE TITLE
Make whole permission item clickable

### ISSUE THREAD

**Issue by dt2patel** [hotwax/users#136]
## What is the motivation for adding/enhancing this feature?

The entire permission item should be clickable and it should also have a hover effect to acknowledge that the users cursor.

adding UI later

**Comment by dt2patel** [comment]
This UI pattern is already done in ATP app, so we just need to replicate that here.

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.11.0. Hence, closing it.
