### ISSUE TITLE
Enhanced User Account Management: Password Reset and Self-Disabling Restrictions

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/users#162]
## What is the motivation for adding/enhancing this feature?
By allowing users to reset their passwords directly, we make it easier for them to maintain secure access to their accounts without needing assistance. Additionally, restricting users from disabling their own accounts helps prevent accidental or malicious account disruptions, ensuring smooth operations and protecting against unauthorized access.

## What are the acceptance criteria?
Users can reset their passwords directly from their account settings without requiring assistance from administrators.
Users are unable to disable their own accounts through the account settings or any other accessible interface.
Attempting to disable one's own account should result in an error message indicating that this action is not permitted.
Administrators retain the ability to disable user accounts as needed for security or administrative purposes.

**Comment by Dhiraj1405** [comment]
Not required as security layer would be breached if non admin user can directly change the password. Hence closing
