### ISSUE TITLE
Improved facility visibility and selection in fulfillment section for facility users.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/users#164]
## What is the motivation for adding/enhancing this feature?
To make it easier for facility users to understand which facility they are working with. By showing the actual facility name instead of generic text, users can quickly identify where they are assigned. Additionally, providing an option to change facilities adds flexibility, allowing users to switch between facilities when needed, making their tasks more efficient.

## What are the acceptance criteria?
The fulfillment section displays the actual name of the facility associated with the facility user instead of generic text.
An option to change the associated facility is provided within the fulfillment section interface.
Facility users can successfully change their associated facility by utilizing the provided option.

## Additional information
https://jam.dev/c/5986e139-30c2-4e9d-856d-c5137e5e285a

**Comment by Dhiraj1405** [comment]
Not doing it for now. Will recreate it when required.
