### ISSUE TITLE
Improve facility display logic on Admin user details page

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/users#173]
## Description
Currently, on the user details page of an admin user, the message "Added to 0 facilities" is displayed, even though the user has access to all facilities. This inconsistency in the displayed information can lead to confusion and misinterpretation of the user's access privileges. To enhance clarity and accuracy, this enhancement proposes improving the facility display logic to accurately reflect the admin user's access to facilities.

## Additional information
https://jam.dev/c/4bd5bc75-bc92-48d2-be92-4544177b8aca

**Comment by Dhiraj1405** [comment]
Will add UI here

**Comment by dt2patel** [comment]
@Adameddy26 can you share if the ability to view all facilities is checked based on a specific permission? Or is it based on security group? I think it's permission, and if so, what is the permission ID that is check.

**Comment by Adameddy26** [comment]
> @Adameddy26 can you share if the ability to view all facilities is checked based on a specific permission? Or is it based on security group? I think it's permission, and if so, what is the permission ID that is check.

STOREFULFILLMENT_ADMIN - If this permission is given to any group, then each user in that group will be able to perform operations for every facility

**Comment by ravilodhi** [comment]
@Adameddy26 @dt2patel 

What should be the action item here? Should we display the count for all facilities for the admin/super user and disable the modal that opens to manage the user's facilities? If not, what should the behavior of the facilities modal be?

**Comment by dt2patel** [comment]
Sorry looks like I forgot to attach UI:
<img width="258" alt="Screenshot 2024-09-04 at 4 30 15 PM" src="https://github.com/user-attachments/assets/be1c1075-d9ef-4241-ae66-09559a57d1cc">

**Comment by Adameddy26** [comment]
Changes verified and working fine in release v1.11.0.  Hence, closing this ticket.
