### ISSUE TITLE
Multiple api calls being made on permissions page

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/users#188]
## Current behavior

When updating permissions for a security group api's are called multiple times

## Expected behavior

Api call should only be done once.

## Steps to reproduce the issue

- Open permissions page and select a security group
- Click on any permission and observe the network tab

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v1.8.0. Hence, closing it.
https://jam.dev/c/e9275eb0-f458-4252-9787-f1c4ddb2a854
