### ISSUE TITLE
Show others category in the permissions page

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/users#209]
## What is the motivation for adding/enhancing this feature?

Currently permissions which are not in any category are not shown in the permissions.

Hide the permission with hidden category and show all others permissions without category in Others category.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Changes verified and working fine in release v1.9.0. Hence, closing this ticket.
https://jam.dev/c/ba4c187c-339f-47eb-a331-8ae74a836179
