### ISSUE TITLE
When scrolling the list page, the page displays empty state if api fails while loading more users

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/users#211]
## Current behavior

When loading more users on the users list page and if the api fails then the page displays an empty state

## Expected behavior

In this case when api fails while loading more users, the previous loaded content should not be removed and empty state should also not get displayed.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v.1.9.0. Hence, closing this ticket.
https://jam.dev/c/f4e4bc7e-b082-4c12-b886-4e04b1a34d32
