### ISSUE TITLE
User is able to perform operations even if user is not having permissions for that specific action

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/users#219]
## Current behavior

If a user does not have specific permission for performing an action, but then also clicking on the feature works as expected. The UI shows that the feature is disabled for the user but still user can click on the same.

## Expected behavior

User should not be able to click on a feature for which the user does not have permissions.

## Steps to reproduce the issue

1. Login with a user that does not have store fulfillment admin permission
2. Go to user details page for any user
3. Check that the show as picker functionality is disable but still user can click on the same

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

Need to identify all the places in the app where this case can be generated and need to fix this everywhere in the app.

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v1.9.0. Hence, closing this ticket.

Before fix - 
https://github.com/hotwax/users/assets/158989293/9881bc5d-71d9-484f-8ceb-e2edaf0c191e

After fix - https://jam.dev/c/afbca4d3-19ef-4662-a763-07382ab23fe1
