### ISSUE TITLE
Toggle Button Displaying Abbreviated Name Instead of Full Name

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/users#226]
## Expected behavior
Full name should be displayed of the option on the toggle button.

## Steps to reproduce the issue
1. Login the app with valid user credentials.
2. Go to permissions tab, select any security group and observe the issue.

## Environment details
App version : v1.9.0
App environment : UAT

## Additional information
https://jam.dev/c/6c2a2d91-de74-4357-9125-eeb3bdd2238d

**Comment by Dhiraj1405** [comment]
Not a blocker, closing for now.
