### ISSUE TITLE
Add permission support for viewing the Permissions tab

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/users#227]
## What is the motivation for adding/enhancing this feature?

Currently any one can access the permissons tab, Need to update permission management for the page to allow users with security view and security admin permissions to access the Permissions tab.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Changes verified in release v1.9.1 and found few issues while verification.

1. Users with only security creation permissions cannot uncheck permissions that are already checked for security groups. However, they can check or uncheck permissions that are currently unchecked.
2. Even though users with only security viewing permissions cannot change the permission status of security groups, when they attempt to check or uncheck, the checkbox appears checked or unchecked, respectively.

Hence, reopening this ticket.

**Comment by Adameddy26** [comment]
> Changes verified in release v1.9.1 and found few issues while verification.
> 
> 1. Users with only security creation permissions cannot uncheck permissions that are already checked for security groups. However, they can check or uncheck permissions that are currently unchecked.
> 2. Even though users with only security viewing permissions cannot change the permission status of security groups, when they attempt to check or uncheck, the checkbox appears checked or unchecked, respectively.
> 
> Hence, reopening this ticket.

Verified the changes in release v.10.0.
When a user within a security group attempts to modify permissions by checking or unchecking options after either the 'Security Update' or 'Security Create' permission is unchecked, the UI incorrectly displays the status of permissions as changed, despite the API failing to apply these modifications on the backend. Additionally, an error toast message appears on the UI in this scenario.

Therefore, assigning it back to dev team.

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.4.3. Hence, closing this ticket.
