### ISSUE TITLE
Streamlined Product Store Management in User Detail Page

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/users#240]
## Current Behavior
In the permissions section of the user detail page, users can add a product store by clicking the 'Add' button.
After adding a product store, if the user clicks on the card ellipses of the added product store, an 'edit' option is visible in the popover.
The 'Add' button and 'Edit' option currently lead to the same modal for selecting a product store on the user detail page. This setup can be confusing and redundant for users.

## Proposed Changes
Remove the 'Edit' option from the product store card popover to simplify the interface.
When no product store is added, prominently display the 'Add' button for selecting and adding a product store.
After adding at least one product store, change the 'Add' button to an 'Edit' button to allow editing of existing product store selections.

**Comment by Adameddy26** [comment]
Verified and working fine v1.11.0. Hence, closing this ticket.

**Comment by dt2patel** [comment]
Need to update and match given UI in Figma:
![Image](https://github.com/user-attachments/assets/80f1600e-8640-4e45-aa23-8018e35ea271)
![Image](https://github.com/user-attachments/assets/5d0829aa-8209-49cf-a9d4-66672c52c6ef)
