### ISSUE TITLE
Inconsistent Error Messaging in Reset Password Modal

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/users#249]
## Current behavior
1. When the user partially enters a new password in the "Confirm New Password" field, then removes it and clicks outside, the message "Passwords do not match" is displayed even though the "Confirm New Password" field is empty.
2. When the user enters the correct password in the "Confirm New Password" field and then removes the password from the "New Password" field, there is no message displayed, whereas it should prompt "Enter new password".

## Expected behavior
1. If the "Confirm New Password" field is empty and the user clicks outside, no error message should be displayed.
2. If the "New Password" field is empty after the user has entered and removed the password, a message stating "Enter new password" should be displayed.

## Steps to reproduce the issue
Login the App with valid user credentials.
Open any user details.
Click reset password button to open the reset password modal.
Enter new password which complies with the password policy.

Case 1 
Enter the first few characters of new password in confirm new password field.
Remove the entered characters and then click outside.
Observe the issue('Passwords do not match' - This message should not be visible as confirm new password field is empty and also user clicked outside it)
Case 2
Enter correct password in confirm new password field.
Remove the password entered in new password field to observe the issue('Enter new password' - This type of message should be displayed)

## Environment details
App version : v1.10.2
App environment : UAT

## Additional information
https://jam.dev/c/780ba499-ca37-4132-a42c-0b5ac52c41c7

**Comment by dt2patel** [comment]
The current behavior seems fine to me. If user was typing something and stopped typing in the confirmation field then assistance will help them know what the nexts step is.

If a new password is not entered in the first place, the confirmation button is disabled which lets the user know that they cannot proceed.

Closing issue since no immediate corrections are needed.
