### ISSUE TITLE
'Add' Button Visible for 'Select Facilities' Field Even When Facility is Already Selected

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/users#252]
## Current behavior
The 'Add' button is visible and clickable even when the facility is already selected, leading to confusion as the user can only change the selected facility but not add more.

## Expected behavior
The 'Add' button should not be visible when a facility is already selected and displayed. The button should only be visible when there is an option to add additional facilities.

## Steps to reproduce the issue
Log in the App with valid user credentials.
Add facility user.
Navigate to the quick setup section.
Observe the 'Select Facilities' field.
Note that the 'Add' button is visible even though a facility is already selected and displayed.

## Environment details
App version : V1.10.2
App environment : UAT

## Additional information
![Screenshot from 2024-08-01 16-47-03](https://github.com/user-attachments/assets/d47af07a-d447-4112-a442-b068528297f0)

**Comment by Dhiraj1405** [comment]
Show manage instead of `Add` as the label. Allowing users to change the selected facilities.

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v1.11.0. Hence, closing this ticket.

**Comment by dt2patel** [comment]
The previous UI here was correct and this ticket should be rolled back

**Comment by Adameddy26** [comment]
Verified in release v1.11.1 and found that the changes are reverted.
