### ISSUE TITLE
User Profile Management and Deletion Permissions

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/users#254]
## Description 
This enhancement adds a permission-based system that lets authorized users change or remove any user's profile picture and delete user accounts. A new permission will be created to handle these tasks, ensuring that only approved users have access. To prevent mistakes, there will be confirmation prompts and audit logs to keep track of all actions.

**Comment by Dhiraj1405** [comment]
No other user will be able to access this functionality. Not required for now
