### ISSUE TITLE
Display spinner inplace of checkbox while permission association with groups is updating.

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/users#260]
## What is the motivation for adding/enhancing this feature?

When we click on the permission item an api gets called for linking/unlinking it with the security group. The checkbox doesn't get updated until app successfully completes.

Here in this case we should show spinner in place of checkbox till permission association api call completes for better user experience.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.11.0. Hence, closing this ticket.
