### ISSUE TITLE
Add ability to link user to multiple security groups

### ISSUE THREAD

**Issue by dt2patel** [hotwax/users#267]
## What is the motivation for adding/enhancing this feature?

Allow users to be linked to multiple security groups.

If they are not added to any then show button for adding to group.

If user has been removed from security groups historically, show option to open modal for historical memberships

Each group has popover option which shows when they were added to the current group as well as option to remove from group.

<img width="1025" alt="Screenshot 2024-08-29 at 4 58 04 PM" src="https://github.com/user-attachments/assets/350ac6c6-4bff-457e-b1dc-9741a2b70bbf">

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.11.0. Hence, closing this ticket.
