### ISSUE TITLE
Empty State Not Displayed When Searching for Hidden Permissions in Permissions Tab

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/users#277]
## Current behavior
The UI remains blank without any indication that no permissions match the search query.

## Expected behavior
An empty state message should be displayed indicating that no results were found

## Steps to reproduce the issue
Navigate to the Permissions tab.
Enter a permission name in the search bar that is hidden.
Observe the search results.

## Environment details
App version : v1.11.0
App environement : UAT

## Additional information
https://jam.dev/c/9cd66000-4cfc-4d28-aea5-b5d88124508f

**Comment by priyanshee1604** [comment]
Tested the functionality of hidden permissions successfully. Created a permission in the **SecurityPermission** entity and verified its visibility in the app. Then, added this permission to the **SecurityGroupPermission** entity with groupId = '**SGC_HIDDEN**', which is responsible for hiding the permission. Upon searching, the records were not displayed, and the message "No records found" appeared as expected.
