### ISSUE TITLE
Permission Re-check on Security Group Change for Fulfillment Section Access in User Details

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/users#278]
## Current behavior
Currently, permissions to access the fulfillment section is not re-fetched when changing the security group.

## Expected behavior
Upon changing the security group, permissions to access the Fulfillment Section should be re-fetched.

## Steps to reproduce the issue
Navigate to find users page.
Select a user and go to its detail page. Add a security group to which STOREFULFILLMENT_ADMIN permission is assigned.
Open the popover options of assigned security group and select remove option.
Check if the permissions for the Fulfillment Section in the user's details are revalidated.

## Environment details
App version : v1.11.0
App environment : UAT

## Additional information
https://jam.dev/c/cafe37ab-7765-4159-a36c-fad13500bb2b

**Comment by dt2patel** [comment]
In general in the users app, user permissions should be treated as transactional data, not cached on login. This is because this app is mostly used to manage user permissions so that will be changing the most.

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.11.1. Hence, closing this ticket.
