### ISSUE TITLE
Migrate user picker making logic to partyRole instead of using partyRelationship

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/users#292]
## What is the motivation for adding/enhancing this feature?

Currenlty we are creating party relationship to assing user as a picker. This result in expired record showing up in Fulfillment assign pciker modal. 

To fix this, we should use partyRole instead of partyRelationship to manage show as picker functionality.

Related Issue: https://github.com/hotwax/fulfillment/issues/802

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by amansinghbais** [comment]
Here the updated status of warehouse picker role might not reflect in Fulfillment app assign picker modal, due to indexing issue.

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.11.1. Hence, closing this ticket.
