### ISSUE TITLE
Security Group History Modal Pre-filled for New User Without Login ID/Password

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/users#297]
## Current behavior
The Security Group History modal is appearing pre-filled with data for the newly created user.

## Expected behavior
For a newly created user, the Security Group History modal should be empty when no login ID or password is set.

## Steps to reproduce the issue
Create a new user without setting the login ID or password.
View the Security Group History of the newly created user.
Observe that the Security Group History modal is pre-filled with data.

## Environment details
App version : v1.11.1
App environment : UAT

## Additional information
https://jam.dev/c/6b48e386-28e9-447e-9b95-06f7fbc6f5c6

**Comment by Adameddy26** [comment]
Assigning this ticket to @priyanshee1604 for verification.
CC: @dt2patel

**Comment by priyanshee1604** [comment]
Verified the issue: The Security Group History modal for a newly created user is empty, as expected.
